# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
